# This is the name of the workflow that will appear in the "Actions" tab of your GitHub repository.
name: Python Application CI

# This section defines when the workflow should be triggered.
on:
  # Run this workflow on every push to the "main" branch.
  push:
    branches: [ "main" ]
  # Also run this workflow on any pull request that targets the "main" branch.
  pull_request:
    branches: [ "main" ]

# A workflow is composed of one or more "jobs" that can run in sequence or in parallel.
jobs:
  # This workflow has a single job called "build".
  build:
    # This job will run on a virtual machine with the latest version of Ubuntu Linux.
    runs-on: ubuntu-latest

    # "steps" are the sequence of tasks that will be executed as part of the job.
    steps:
      # Step 1: Checks out your repository's code onto the runner, allowing the job to access it.
      - name: Check out repository code
        uses: actions/checkout@v3

      # Step 2: Sets up a specific version of Python on the runner.
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # Step 3: Installs the project's dependencies from your requirements.txt file.
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      # Step 4: Runs your test suite using the pytest command. If any test fails, this step will fail, and the workflow run will be marked as a failure.
      - name: Run tests with pytest
        run: pytest